name: jawaramobile_1
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.2.2
  data_table_2: ^2.5.10
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0
  go_router: ^16.2.4
  image_picker: ^0.8.7+6
  file_picker: ^8.0.3
  fl_chart: ^1.1.1

  # Tambahan backend & utilities
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Testing + code generator
  mockito: ^5.6.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
